@base_address = http://localhost:5171

POST {{base_address}}/api/people
Content-Type: application/json

{
    "id":null,
    "Name": "blah",
    "email": "abc@x.com",
    "age": null,
    "password":"abc1"
}

###
